### ISSUE TITLE
sqlserver 替换mysql 报错

### ISSUE THREAD

**Issue by Klar-t** [kalvinGit/kvf-admin#1]
![image](https://user-images.githubusercontent.com/26728510/78215035-2d092f00-74e9-11ea-9595-310844e61e31.png)
limit 错误，但是在xml中没有找到limit语句
能解答一下么

**Comment by kalvinGit** [comment]
在MybatisPlusConfig.java类分页配置bean中，把page.setDialectType("mysql");注释掉，或者配置你对应的数据库类型
