### ISSUE TITLE
流程过程错误

### ISSUE THREAD

**Issue by wonderfulMorty** [kalvinGit/kvf-admin#5]
在请假流程发起请假的时候，显示错误
Unknown property used in expression: ${result == 'access'}

**Comment by kalvinGit** [comment]
你流程配置了流程变量【result】，但是你表单提交没有提交这个变量，所以报错。

**Comment by yeyanghua** [comment]
也是请假流程，使用了排他网关。并且配置了表单，也会宝这个错误Unknown property used in expression :${day >=2}
![图片](https://user-images.githubusercontent.com/23163071/103252598-7c1cbb80-49b8-11eb-90be-b5aa5e2f453d.png)
![图片](https://user-images.githubusercontent.com/23163071/103252605-82ab3300-49b8-11eb-9715-33c8cc35f047.png)
![图片](https://user-images.githubusercontent.com/23163071/103252610-850d8d00-49b8-11eb-9a99-38d8872b723b.png)

图片可能显示不出来，已经在您的码云上提过了。有空辛苦看下

**Comment by kalvinGit** [comment]
问题已解决。
原因：
提交任务时，没有将表单数据填充到activiti流转变量中，从而导致找不到变量属性
