### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [kalvinGit/kvf-admin#7]
hi，我们对您分享的这个工单系统项目十分感兴趣，希望能与您进根据此项目进行课程合作，但是 github 上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系；或者可以直接联系我们的官方合作微信号 “shiyanloukecheng”，期待您的回复。

**Comment by kalvinGit** [comment]
微信：kalvinwx
